/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */
package org.fusesource.scalate.console

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._
import org.fusesource.scalate.wikitext.PygmentizeHelpers._

object $_scalate_$console_scaml {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    import _root_.org.fusesource.scalate.support.RenderHelper.{sanitize=>$_scalate_$_sanitize, preserve=>$_scalate_$_preserve, indent=>$_scalate_$_indent, smart_sanitize=>$_scalate_$_smart_sanitize, attributes=>$_scalate_$_attributes}
    ;{
      implicit val context: _root_.org.fusesource.scalate.servlet.ServletRenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      //
      //       Copyright (C) 2009-2011 the original author or authors.

      //       See the notice.md file distributed with this work for additional

      //       information regarding copyright ownership.

      //
      //       Licensed under the Apache License, Version 2.0 (the "License");

      //       you may not use this file except in compliance with the License.

      //       You may obtain a copy of the License at

      //
      //           http://www.apache.org/licenses/LICENSE-2.0

      //
      //       Unless required by applicable law or agreed to in writing, software

      //       distributed under the License is distributed on an "AS IS" BASIS,

      //       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

      //       See the License for the specific language governing permissions and

      //       limitations under the License.

      //
      ;{
        val consoleHelper: ConsoleHelper = $_scalate_$_context.attributeOrElse("consoleHelper", new ConsoleHelper(context) )
        import consoleHelper._
                if (isDevelopmentMode)
{
          $_scalate_$_context << ( "<div id=\"scalate-console\">\n" );
                    if (!optionEnabled("console"))
{
            $_scalate_$_context << ( "  <div class=\"toggle show\">\n    <a" );
            $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                "href"
              ,
                                enableLink("console")

              ), (
                "class"
              ,
                "consoleLink"
              ), (
                "title"
              ,
                "Show the Scalate Console"
            ) ) )
            $_scalate_$_context << ( ">\n      <img" );
            $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                "src"
              ,
                                uri("/images/scalate/project-icon-24x24.png")

            ) ) )
            $_scalate_$_context << ( "/>\n      <img" );
            $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                "src"
              ,
                                uri("/images/scalate/plus.png")

            ) ) )
            $_scalate_$_context << ( "/>\n    </a>\n  </div>\n" );
          }
                    else
{
            $_scalate_$_context << ( "  <div class=\"toggle hide\">\n    <a" );
            $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                "href"
              ,
                                disableLink("console")

              ), (
                "class"
              ,
                "consoleLink hide"
              ), (
                "title"
              ,
                "Hide the Scalate Console"
            ) ) )
            $_scalate_$_context << ( ">\n      <img" );
            $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                "src"
              ,
                                uri("/images/scalate/project-icon-24x24.png")

            ) ) )
            $_scalate_$_context << ( "/>\n      Scalate Console\n      <img" );
            $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                "src"
              ,
                                uri("/images/scalate/minus.png")

            ) ) )
            $_scalate_$_context << ( "/>\n    </a>\n  </div>\n  <div class=\"archetypes\">\n    <p>Create</p>\n    " );
            $_scalate_$_context << ( $_scalate_$_indent ( "    ", $_scalate_$_context.value(
               render("/WEB-INF/scalate/archetypes/menu.scaml")
            ) ) );
            /*
             *             - if (newTemplateName.isDefined && resourceClassName.isDefined)

             *               - val newName = newTemplateName.get

             *               %h3 Create New Custom Template

             *               %p Create a new template called #{newName} from archetype

             *               %ul

             *                 - for (a <- archetypes)

             *                   %li

             *                     %form(action={uri("/scalate/createTemplate")} method="post")

             *                       %input(type="hidden" name="archetype" value={a.archetype})

             *                       %input(type="hidden" name="newTemplateName" value={newName})

             *                       %input(type="hidden" name="resourceClass" value={resourceClassName.get})

             *                       %input(type="submit" value={a.name})

             */
            $_scalate_$_context << ( "\n  </div>\n" );
                        val sourceFile = resourceSourceFile

                        if (sourceFile.isDefined)
{
              $_scalate_$_context << ( "  <div class=\"resources\">\n    <p>Resources</p>\n" );
                            val file = resourceSourceFile.get

              $_scalate_$_context << ( "    <ul>\n      <li>\n" );
                            println("Found file: " + file)

              $_scalate_$_context << ( "        " );
              $_scalate_$_context << ( $_scalate_$_indent ( "        ", $_scalate_$_context.value(
                                 editFileLink(file.getAbsolutePath)
 {
                  $_scalate_$_context << ( "        " );
                  $_scalate_$_context << ( $_scalate_$_indent ( "        ", $_scalate_$_context.value(
                     shorten(file)
                  ) ) );
                  $_scalate_$_context << ( "\n" );
                }
              ) ) );
              $_scalate_$_context << ( "\n      </li>\n    </ul>\n  </div>\n" );
            }
                        if (!templates.isEmpty)
{
              $_scalate_$_context << ( "  <div class=\"templates\">\n    <p>Templates</p>\n    <ul>\n" );
                            for (template <- templates)
{
                                val link = editLink(template)
{
                  $_scalate_$_context << ( "      " );
                  $_scalate_$_context << ( $_scalate_$_indent ( "      ", $_scalate_$_context.value(
                     template.stripPrefix("/")
                  ) ) );
                  $_scalate_$_context << ( "\n" );
                }
                                if (!link.isEmpty)
{
                  $_scalate_$_context << ( "      <li>\n        " );
                  $_scalate_$_context << ( $_scalate_$_indent ( "        ", $_scalate_$_context.value(
                     link
                  ) ) );
                  $_scalate_$_context << ( "\n      </li>\n" );
                }
              }
              $_scalate_$_context << ( "    </ul>\n  </div>\n" );
            }
                        if (!layouts.isEmpty)
{
              $_scalate_$_context << ( "  <div class=\"layouts\">\n    <p>Layouts</p>\n    <ul>\n" );
                            for (layout <- layouts)
{
                $_scalate_$_context << ( "      <li>\n        " );
                $_scalate_$_context << ( $_scalate_$_indent ( "        ", $_scalate_$_context.value(
                                     editLink(layout)
 {
                    $_scalate_$_context << ( "        " );
                    $_scalate_$_context << ( $_scalate_$_indent ( "        ", $_scalate_$_context.value(
                       layout.stripPrefix("/")
                    ) ) );
                    $_scalate_$_context << ( "\n" );
                  }
                ) ) );
                $_scalate_$_context << ( "\n      </li>\n" );
              }
              $_scalate_$_context << ( "    </ul>\n  </div>\n" );
            }
            $_scalate_$_context << ( "  <form" );
            $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                "action"
              ,
                                uri("/scalate/invalidateCachedTemplates")

              ), (
                "method"
              ,
                "post"
            ) ) )
            $_scalate_$_context << ( ">\n    <input type=\"submit\" value=\"Clear Cache\"/>\n  </form>\n" );
                        if (!optionEnabled("attributes"))
{
              $_scalate_$_context << ( "  <div class=\"toggle show\">\n    <a" );
              $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                  "href"
                ,
                                    enableLink("attributes")

                ), (
                  "title"
                ,
                  "Show the Attributes"
              ) ) )
              $_scalate_$_context << ( ">\n      Attributes\n      <img" );
              $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                  "src"
                ,
                                    uri("/images/scalate/plus.png")

              ) ) )
              $_scalate_$_context << ( "/>\n    </a>\n  </div>\n" );
            }
                        else
{
              $_scalate_$_context << ( "  <div class=\"toggle hide\">\n    <a" );
              $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                  "href"
                ,
                                    disableLink("attributes")

                ), (
                  "title"
                ,
                  "Hide the Attributes"
              ) ) )
              $_scalate_$_context << ( ">\n      Attributes\n      <img" );
              $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                  "src"
                ,
                                    uri("/images/scalate/minus.png")

              ) ) )
              $_scalate_$_context << ( "/>\n    </a>\n  </div>\n  <div class=\"attributes\">\n    <table id=\"attributes\">\n      <tr>\n        <th>Name</th>\n        <th>Value</th>\n      </tr>\n" );
                            for (k <- attributeKeys)
{
                                if (k != "body")
{
                  $_scalate_$_context << ( "      <tr>\n        <td id=\"name\">\n          " );
                  $_scalate_$_context << ( $_scalate_$_indent ( "          ", $_scalate_$_context.value(
                     k
                  ) ) );
                  $_scalate_$_context << ( "\n        </td>\n        <td id=\"value\">\n          " );
                  $_scalate_$_context << ( $_scalate_$_indent ( "          ", $_scalate_$_context.value(
                     attributes(k)
                  ) ) );
                  $_scalate_$_context << ( "\n        </td>\n      </tr>\n" );
                }
              }
              $_scalate_$_context << ( "    </table>\n  </div>\n" );
            }
                        if( attributes("body")!=null )
{
                            if (!optionEnabled("body"))
{
                $_scalate_$_context << ( "  <div class=\"toggle show\">\n    <a" );
                $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                    "href"
                  ,
                                        enableLink("body")

                  ), (
                    "title"
                  ,
                    "Show the Body"
                ) ) )
                $_scalate_$_context << ( ">\n      Body\n      <img" );
                $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                    "src"
                  ,
                                        uri("/images/scalate/plus.png")

                ) ) )
                $_scalate_$_context << ( "/>\n    </a>\n  </div>\n" );
              }
                            else
{
                $_scalate_$_context << ( "  <div class=\"toggle hide\">\n    <a" );
                $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                    "href"
                  ,
                                        disableLink("body")

                  ), (
                    "title"
                  ,
                    "Hide the Body"
                ) ) )
                $_scalate_$_context << ( ">\n      Body\n      <img" );
                $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                    "src"
                  ,
                                        uri("/images/scalate/minus.png")

                ) ) )
                $_scalate_$_context << ( "/>\n    </a>\n  </div>\n  <div class=\"body\">\n    <pre class=\"brush: html\">" );
                $_scalate_$_context << ( $_scalate_$_preserve ( $_scalate_$_context.valueEscaped(
                   attributes("body")
                ) ) );
                $_scalate_$_context << ( "</pre>\n    " );
                $_scalate_$_context << ( $_scalate_$_indent ( "    ", $_scalate_$_context.value ( _root_.org.fusesource.scalate.filter.FilterRequest("javascript", $_scalate_$_context.capture { 
                  $_scalate_$_context << ( "SyntaxHighlighter.all()" );
                } ) ) ) );
                $_scalate_$_context << ( "\n  </div>\n" );
              }
            }
                        if (!optionEnabled("sysProp"))
{
              $_scalate_$_context << ( "  <div class=\"toggle show\">\n    <a" );
              $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                  "href"
                ,
                                    enableLink("sysProp")

                ), (
                  "title"
                ,
                  "Show the System Properties"
              ) ) )
              $_scalate_$_context << ( ">\n      System Properties\n      <img" );
              $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                  "src"
                ,
                                    uri("/images/scalate/plus.png")

              ) ) )
              $_scalate_$_context << ( "/>\n    </a>\n  </div>\n" );
            }
                        else
{
              $_scalate_$_context << ( "  <div class=\"toggle hide\">\n    <a" );
              $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                  "href"
                ,
                                    disableLink("sysProp")

                ), (
                  "title"
                ,
                  "Hide the System Properties"
              ) ) )
              $_scalate_$_context << ( ">\n      System Properties\n      <img" );
              $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
                  "src"
                ,
                                    uri("/images/scalate/minus.png")

              ) ) )
              $_scalate_$_context << ( "/>\n    </a>\n  </div>\n  <div class=\"systemProperties\">\n    <table id=\"systemProperties\">\n      <tr>\n        <th>Name</th>\n        <th>Value</th>\n      </tr>\n" );
                            for ((k,v) <- systemProperties)
{
                $_scalate_$_context << ( "      <tr>\n        <td id=\"name\">\n          " );
                $_scalate_$_context << ( $_scalate_$_indent ( "          ", $_scalate_$_context.value(
                   k
                ) ) );
                $_scalate_$_context << ( "\n        </td>\n        <td id=\"value\">\n          " );
                $_scalate_$_context << ( $_scalate_$_indent ( "          ", $_scalate_$_context.value(
                   v
                ) ) );
                $_scalate_$_context << ( "\n        </td>\n      </tr>\n" );
              }
              $_scalate_$_context << ( "    </table>\n  </div>\n" );
            }
          }
          $_scalate_$_context << ( "</div>\n" );
        }
      }
    }
  }
}


class $_scalate_$console_scaml extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$console_scaml.$_scalate_$render(context)
}
